routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserJsonController;
use App\Http\Controllers\SwappingController;
use App\Http\Controllers\CountedController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard1', [App\Http\Controllers\DashboardController::class, 'dashboard1'])->name('dashboard1');
Route::get('/dashboard2', [App\Http\Controllers\DashboardController::class, 'dashboard2'])->name('dashboard2');
Route::get('/dashboard3', [App\Http\Controllers\DashboardController::class, 'dashboard3'])->name('dashboard3');
Route::get('/users', [App\Http\Controllers\UserController::class, 'index'])->name('index');
Route::get('/add/users', [App\Http\Controllers\UserController::class, 'create'])->name('create');
Route::post('/users/store', [App\Http\Controllers\UserController::class, 'store'])->name('store');


Route::resource('user', UserController::class);
Route::resource('product', ProductController::class);
Route::resource('userjson', UserJsonController::class);
Route::resource('swapping', SwappingController::class);
Route::resource('counted', CountedController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */

    protected $fillable = [
        'name',
        'email',
        'password',
        'isactive',
        'isadmin',
        'islogin'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Models\User;
use App\Providers\RouteServiceProvider;
use Illuminate\Support\Facades\Http;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['title'] = 'Data User';
        $data['q'] = $request->q;
        $data['rows'] = User::all();
       
        return view('users.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $data['title'] = 'Tambah User';
        $data['levels'] = [1 => 'Admin', 0 => 'User'];
        return view('users.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'password' => 'required',
            'level' => 'required'
            
        ]);

        $user = new User();
        $user->name     = $request->name;
        $user->email    = $request->email;
        $user->password = Hash::make($request->password);
        $user->isactive = true;
        $user->isadmin  = $request->level;
        $user->islogin  = false;
        $user->save();
        return redirect('user')->with('success', 'Tambah Data Berhasil');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user){
        $data['title'] = 'Ubah User';
        $data['row'] = $user;
        $data['levels'] = [1 => 'Admin', 0 => 'User'];
        return view('users.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user){
        $request->validate([
            'name' => 'required',
            'email' => 'required'
        ]);

        $user->name = $request->name;
        $user->email = $request->email;
        $user->isadmin  = $request->level;
        $user->save();
        return redirect('user')->with('success', 'Ubah Data Berhasil');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $idUser = Auth::user()->id;
        if ($idUser!=$user->id){
            $delete = User::where('id', $user->id)->delete();
        }
        
        return redirect('user')->with('success', 'Hapus Data Berhasil');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
  <body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed"></body>
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Add New</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><i class="nav-icon fas fa-users"></i> Manage Users</li>
              <li class="breadcrumb-item active"><i class="far fa-user nav-icon"></i> Users</li>
              <li class="breadcrumb-item active">Add New</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-2"></div>
          <div class="col-md-8">
            
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">New user</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form class="form-horizontal" method="post" action="{{ route('user.store') }}" >
                @csrf
                <div class="card-body">
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text">@</span>
                      </div>
                      <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus placeholder="Username">
                    </div>
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                      </div>
                      <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" placeholder="Email">
                    </div>
                    <div class="input-group mb-3">
                      <div class="input-group-append">
                          <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                          </div>
                      </div>
                      <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">
                    </div>
                    <div class="input-group mb-3">
                      <div class="input-group-append">
                          <div class="input-group-text">
                            <i class="fa fa-cog fa-spin"></i>
                          
                          </div>
                      </div>
                      <select class="form-control" name="level" id="level" />
                        @foreach($levels as $key => $val)
                          @if($key==old('level'))
                            <option value="{{ $key }}" selected>{{ $val }}</option>
                          @else
                            <option value="{{ $key }}">{{ $val }}</option>
                          @endif
                        @endforeach
                      </select>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-info">Create</button>
                  <a href="{{ route('user.index') }}" class="btn btn-default float-right">Cancel</a>
                </div>
                <!-- /.card-footer -->
              </form>
            </div>

          </div>
          <div class="col-md-2"></div>
         
        </div>
      </div>
    </section>

 
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
  <body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed"></body>
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Add New</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><i class="nav-icon fas fa-users"></i> Manage Users</li>
              <li class="breadcrumb-item active"><i class="far fa-user nav-icon"></i> Users</li>
              <li class="breadcrumb-item active">Add New</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-2"></div>
          <div class="col-md-8">
            
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">New user</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form class="form-horizontal" method="post" action="{{ route('user.update', $row) }}" >
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text">@</span>
                      </div>
                      <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name', $row->name) }}" required autocomplete="name" placeholder="Username">
                    </div>
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                      </div>
                      <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('name', $row->email) }}" required autocomplete="email" placeholder="Email">
                    </div>
                    
                    <div class="input-group mb-3">
                      <div class="input-group-append">
                          <div class="input-group-text">
                            <i class="fa fa-cog fa-spin"></i>
                          
                          </div>
                      </div>
                      <select class="form-control" name="level" id="level" />
                      @foreach($levels as $key => $val)
                        @if($key==old('level', $row->level))
                        <option value="{{ $key }}" selected>{{ $val }}</option>
                        @else
                        <option value="{{ $key }}">{{ $val }}</option>
                        @endif
                      @endforeach
                      </select>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-info">Create</button>
                  <a href="{{ route('user.index') }}" class="btn btn-default float-right">Cancel</a>
                </div>
                <!-- /.card-footer -->
              </form>
            </div>

          </div>
          <div class="col-md-2"></div>
         
        </div>
      </div>
    </section>

 
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
  <body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed"></body>
  <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><i class="far fa-user nav-icon"></i> Users</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><i class="nav-icon fas fa-users"></i> Manage Users</li>
              <li class="breadcrumb-item active"><i class="far fa-user nav-icon"></i> Users</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-1"></div>
          <div class="col-10">
            
            <div class="card">
              <!-- <div class="card-header">
                <h3 class="card-title"><a href="{{ url('/add/users') }}" class="btn btn-block btn-outline-success">Add New</a></h3>
              </div> -->
              <div class="card-header">
                <form class="form-inline">
                    <!-- <div class="form-group mr-1">
                        <input class="form-control" type="text" name="q" value="{{ $q}}" placeholder="Pencarian..." />
                    </div>
                    <div class="form-group mr-1">
                        <button class="btn btn-success">Refresh</button>
                    </div> -->
                    <div class="form-group mr-1">
                        <a class="btn btn-primary" href="{{ route('user.create') }}">Tambah </a>
                    </div>
                </form>
            </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                          <th>No</th>
                          <th>Name</th>
                          <th>Email</th>
                          <th>Level</th>
                          <th>Action</th>
                      </tr>
                    </thead>
                    <?php $no = 1 ?>
                    @foreach($rows as $row)
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>{{ $row->name }}</td>
                        <td>{{ $row->email }}</td>
                        <td>{{ $row->isadmin }}</td>
                        <td>
                            <a class="btn btn-sm btn-warning" href="{{ route('user.edit', $row) }}"><i class="fa fa-edit"></i></a>
                            <form method="POST" action="{{ route('user.destroy', $row) }}" style="display: inline-block;">
                                @csrf
                                @method('DELETE')
                                
                                <button class="btn btn-sm btn-danger" onclick="return confirm('Hapus Data?')"><i class='fa fa-trash'></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                  </tbody>
                  
                </table>

              </div>
              <!-- /.card-body -->
            </div>
          </div>
          <div class="col-1"></div>
        </div>
        <div class="row">
        <div class="col-1"></div>
        <div class="col-md-10">
            <div class="card card-default">
              <div class="card-header">
                <h3 class="card-title">
                  <i class="fas fa-exclamation-triangle"></i>
                  Alerts
                </h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                
                <div class="alert alert-success alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <h5><i class="icon fas fa-check"></i> Ketentuan</h5>
                  Tidak Bisa MengHapus User Yang Sedang Login
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
        <div class="col-1"></div>
        
      </div>
    </section>
  
    
 
@endsection

resources/views/users/index_json.blade.php
@extends('layouts.app')

@section('content')
  <body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed"></body>
  <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><i class="far fa-user nav-icon"></i> Users Format Json</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><i class="nav-icon fas fa-users"></i> API User</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-check"></i> Ketentuan Response All User In Format Json </h5>
                Reponse Json Ini akan bertambah/berubah/berkurang sesuai dengan data user, untuk perubahan silahkan operasionalkan menu Users.
            </div>
          </div>
          <div class="col-md-12">
            <div class="card card-outline card-info">
              <div class="card-header">
                <h3 class="card-title">
                  Response All User In Format Json
                </h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                {{ $data }}
              </div>
              
            </div>
          </div>
          <div class="col-md-12">
          
            
            <div class="card">
              <!-- <div class="card-header">
                <h3 class="card-title"><a href="{{ url('/add/users') }}" class="btn btn-block btn-outline-success">Add New</a></h3>
              </div> -->
              
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                          <th>No</th>
                          <th>Name</th>
                          <th>Email</th>
                          <th>Level</th>
                      </tr>
                    </thead>
                    <?php $no = 1 ?>
                    @foreach($rows as $row)
                      <tr>
                      <td>{{ $no++ }}</td>
                        <td>{{ $row->name }}</td>
                        <td>{{ $row->email }}</td>
                        <td>{{ $row->isadmin }}</td>
                          
                      </tr>
                    @endforeach
                  </tbody>
                  
                </table>
              </div>
              <!-- /.card-body -->
            </div>
          
          </div>
        </div>
      </div>
    </section>
    
    
 
@endsection