routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserJsonController;
use App\Http\Controllers\SwappingController;
use App\Http\Controllers\CountedController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard1', [App\Http\Controllers\DashboardController::class, 'dashboard1'])->name('dashboard1');
Route::get('/dashboard2', [App\Http\Controllers\DashboardController::class, 'dashboard2'])->name('dashboard2');
Route::get('/dashboard3', [App\Http\Controllers\DashboardController::class, 'dashboard3'])->name('dashboard3');
Route::get('/users', [App\Http\Controllers\UserController::class, 'index'])->name('index');
Route::get('/add/users', [App\Http\Controllers\UserController::class, 'create'])->name('create');
Route::post('/users/store', [App\Http\Controllers\UserController::class, 'store'])->name('store');


Route::resource('user', UserController::class);
Route::resource('product', ProductController::class);
Route::resource('userjson', UserJsonController::class);
Route::resource('swapping', SwappingController::class);
Route::resource('counted', CountedController::class);

app/Http/Controllers/SwappingController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Providers\RouteServiceProvider;
use Illuminate\Support\Facades\Http;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Response;

class SwappingController extends Controller
{
    
    public function index(Request $request){
        $response = response()->json([
            'status' => Response::HTTP_OK,
            'message'=> 'Get User Format Json',
            'data'   => User::all()
        ],Response::HTTP_OK);
        $data = $response->original;
       
        return view('swapping.index')->with('data', json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    }

    public function store(Request $request){
        $nilai_a = $request->nilai_a;
        $nilai_b = $request->nilai_b;

        $data['nilai_a'] = $nilai_a;
        $data['nilai_b'] = $nilai_b;
        $data['hasil1'] = intval($nilai_a) + intval($nilai_b);
        $data['hasil2'] = intval($data['hasil1']) - intval($nilai_b);
        $data['hasil3'] = intval($data['hasil1']) - intval($data['hasil2']);
        
        return view('swapping.swapping',$data);
    }
}

resources/views/swapping/index.blade.php
@extends('layouts.app')

@section('content')
  <body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed"></body>
  <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><i class="far fa-user nav-icon"></i> Swapping Two variable</h1>
          </div>
          
      </div><!-- /.container-fluid -->
    </section>

    <section class="content">
      <div class="container-fluid">
        <div class="row">
          
          
          <div class="col-md-6">
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Swapping Value</h3>
              </div>
              <form class="form-horizontal" method="post" action="{{ route('swapping.store') }}" >
                @csrf
                <div class="card-body">
                    <div class="input-group mb-3">
                      <input id="nilai_a" name="nilai_a" type="number" class="form-control" placeholder="Input Value A">
                    </div>
                    <div class="input-group mb-3">
                      
                    <input id="nilai_b" name="nilai_b" type="number" class="form-control" placeholder="Input Value B">
                    </div>
                    
                    
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <!-- <button type="submit" class="btn btn-info">Create</button> -->
                  <input type="submit" name="submit" value="Swapping" class="btn btn-info" /> 
                </div>
                <!-- /.card-footer -->
              </form>
            </div>
          </div>
          
        </div>
       
        
      </div>
    </section>
@endsection

resources/views/swapping/swapping.blade.php
@extends('layouts.app')

@section('content')
  <body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed"></body>
  <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><i class="far fa-user nav-icon"></i> Swapping Two variable</h1>
          </div>
          
      </div><!-- /.container-fluid -->
    </section>

    <section class="content">
      <div class="container-fluid">
        <div class="row">
        
          <div class="col-md-12">
            <div class="card card-outline card-info">
              <div class="card-header">
                <h3 class="card-title">
                  Swipping Proccess
                </h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
                $A = {{ $nilai_a }}; <br>
                $B = {{ $nilai_b }}; <br>
                Proses 1:<br>
                    &nbsp;&nbsp;&nbsp;$A = $A({{ $nilai_a }}) + $B({{ $nilai_b }})  => Hasil A Adalah {{ $hasil1 }}<br>
                Proses 2:<br>
                    &nbsp;&nbsp;&nbsp;$B = $A({{ $hasil1 }}) - $B({{ $nilai_b }})  => Hasil B Adalah {{$hasil2}}<br>
                Proses 3:<br>
                    &nbsp;&nbsp;&nbsp;$A = $A({{ $hasil1 }}) - $B({{$hasil2}})  => Hasil A Adalah {{ $hasil3 }}<br><br>

                Nilai Awal A Adalah {{ $nilai_a }}  || Hasil Akhir A Adalah {{$hasil3}}<br>
                Nilai Awal B Adalah {{ $nilai_b }}  || Hasil Akhir B Adalah {{$hasil2}}<br>
              </div>
              
            </div>
          
          </div>
          
        </div>
       
        
      </div>
    </section>
@endsection